parameters:

services:
    app.manager.extract:
        class: AppBundle\Manager\ExtractManager
        arguments:
            - '%kernel.root_dir%'

    app.manager.xls_export:
        class: AppBundle\Manager\XlsExportManager
        arguments:
            - '%kernel.root_dir%'
